[package]
name = "Rust-AES-Proofs"
version = "0.1.0"
authors = [
    "Jeremiah Wagstaff <jeremiah.wagstaff@gmail.com>",
    "Nazar Mokrynskyi <nazar@mokrynskyi.com>"
]
edition = "2018"

[dependencies]
