[package]
name = "Rust-AES-Proofs"
version = "0.1.0"
authors = [
    "Jeremiah Wagstaff <jeremiah.wagstaff@gmail.com>",
    "Nazar Mokrynskyi <nazar@mokrynskyi.com>"
]
edition = "2018"

[dependencies]
# TODO: Absorb this dependency
aes-benchmarks = {git = "https://github.com/subspace/aes-benchmarks.git"}
rayon = "1.3.0"
